### ISSUE TITLE
Error in CommunicatorFactory

### ISSUE THREAD

**Issue by himanshu2047** [convict-git/KoraKaagaz#136]
`CommunicatorFactory.getCommunicator()` is throwing NULL Pointer Exception.

Error:

```
Exception in thread "main" java.lang.NullPointerException
	at networking.CommunicatorFactory.getCommunicator(CommunicatorFactory.java:76)
	at processing.server.main.MainServer.main(MainServer.java:40)
```
@sravand123

**Comment by himanshu2047** [comment]
Resolved now, As networking module now have given two types of communicator, they told to call `getClientInfo()` before `getCommunicator()` to solve this error.
